---
development:
  cloud_name: darri
  api_key: '747542586963287'
  api_secret: ksp7Yh-1CTojWS7HiTaZTIjnN6c
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: darri
  api_key: '747542586963287'
  api_secret: ksp7Yh-1CTojWS7HiTaZTIjnN6c
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: darri
  api_key: '747542586963287'
  api_secret: ksp7Yh-1CTojWS7HiTaZTIjnN6c
  enhance_image_tag: true
  static_image_support: false